### PR TITLE
Fix: Replaced `[inaudible]` with `lot`

### PR DESCRIPTION
**Pull request by capnslipp**
Not proper English, but makes sense with the words that follow (“lot of rendering possibilities”) and with the slide text (“Full featured rendering”).

### CODE REVIEW

**Comment by natecook1000** [comment]
Thanks so much, @capnslipp! 👏 👏 👏  Can I offer you committing privileges on this repo?

**Comment by capnslipp** [comment]
Absolutely.  It would be my honor to contribute further.

**Comment by natecook1000** [comment]
Done! 🎉

**Comment by capnslipp** [comment]
Good to know.  Thanks again!

**Pull request merged**
